print('olá, mundo')
print('santos é o maior time do mundo')
print('neymar é meu fã')
print('messi aprendeu a jogar bola cmg')
print('cr7 é santista')
print('preto é a melhor cor')
print('palmeiras nao tem mundial')
print('sou mais o sol')
print('corinthians é o menor de sp')
print('rei pelé')
